# Tên catalog Trino sẽ là 'iceberg'
connector.name=iceberg
iceberg.catalog.type=rest
# Kết nối đến Iceberg REST Catalog service
iceberg.rest-catalog.uri=http://172.20.0.5:8181
iceberg.rest-catalog.warehouse=highlands-coffee-warehouse
# # Cấu hình MinIO/S3
# iceberg.s3.endpoint=http://minio:9000
# iceberg.s3.path-style-access=true

# # Thông tin xác thực MinIO
# iceberg.s3.aws-access-key=minioadmin
# iceberg.s3.aws-secret-key=minioadmin

# Cấu hình MinIO/S3
hive.s3.endpoint=http://172.20.0.4:9000
hive.s3.path-style-access=true

# Thông tin xác thực MinIO
hive.s3.aws-access-key=minioadmin
hive.s3.aws-secret-key=minioadmin

# # THUỘC TÍNH S3 TIÊU CHUẨN CỦA TRINO
# # Trino sẽ sử dụng các thuộc tính s3.* để kết nối MinIO
# # 1. Endpoint và Path Style Access (Rất quan trọng cho MinIO)
# s3.endpoint=http://172.20.0.4:9000
# s3.path-style-access=true

# # 2. Thông tin xác thực MinIO
# s3.aws-access-key=minioadmin
# s3.aws-secret-key=minioadmin

# # 3. Vô hiệu hóa SSL nếu cần (để kết nối HTTP)
# s3.ssl.enabled=false



# CREATE SCHEMA iceberg.test_new_schema WITH (location = 's3://highlands-coffee-warehouse/test_new_schema');
# CREATE TABLE iceberg.test_new_schema.sample_data (
#      id INT,
#      name VARCHAR
#       );


# INSERT INTO iceberg.test_new_schema.sample_data (id, name)
#      VALUES (1, 'Espresso'), (2, 'Latte');