# Spark Defaults for Iceberg + MinIO (Optimized)
# --------------------------------------------------------------------------------------
spark.master                              local[*]
spark.driver.memory                       2g
spark.executor.memory                     2g
spark.serializer                          org.apache.spark.serializer.KryoSerializer
spark.sql.adaptive.enabled                true
spark.sql.adaptive.coalescePartitions.enabled true


# Iceberg Extensions and REST Catalog Configuration
spark.sql.extensions       org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.defaultCatalog               							highlands-coffee-catalog
spark.sql.catalogImplementation        							in-memory
spark.sql.catalog.highlands_coffee_catalog.type 				rest
spark.sql.catalog.highlands-coffee-catalog.io-impl         	org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.highlands-coffee-catalog.s3.endpoint          http://minio:9000
spark.sql.catalog.highlands-coffee-catalog.s3.access-key-id     minioadmin
spark.sql.catalog.highlands-coffee-catalog.s3.secret-access-key minioadmin
spark.sql.catalog.highlands-coffee-catalog.s3.path-style-access true
spark.sql.catalog.highlands-coffee-catalog.s3.region            us-east-1
spark.sql.catalog.highlands-coffee-catalog       		  org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.highlands-coffee-catalog.catalog-impl   org.apache.iceberg.rest.RESTCatalog
spark.sql.catalog.highlands-coffee-catalog.uri                  http://iceberg-rest:8181
spark.sql.catalog.highlands-coffee-catalog.warehouse  		s3://highlands-coffee-warehouse/



# Cấu hình này áp dụng cho HỆ THỐNG TỆP MinIO cho tất cả các hoạt động đọc ghi/ thao tác với #actual data
spark.hadoop.fs.s3a.impl                  	org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.region 					us-east-1
spark.hadoop.fs.s3a.endpoint              	http://minio:9000
spark.hadoop.fs.s3a.access.key            	minioadmin
spark.hadoop.fs.s3a.secret.key            	minioadmin
spark.hadoop.fs.s3a.connection.ssl.enabled 	false
spark.hadoop.fs.s3a.path.style.access     	true






