FROM apache/airflow:2.9.0

# Switch to root user for installation
USER root

# Set environment variables
ENV SPARK_HOME=/opt/spark_home
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin
#ENV PYSPARK_PYTHON=python3
#ENV PYSPARK_DRIVER_PYTHON=python3
ENV SPARK_VERSION=3.5.5
ENV SPARK_MAJOR_VERSION=3.5
ENV ICEBERG_VERSION=1.9.0

# Update repository sources and install dependencies
RUN echo "deb http://deb.debian.org/debian bullseye main contrib non-free" > /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian-security bullseye-security main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian bullseye-updates main contrib non-free" >> /etc/apt/sources.list && \
    apt-get update -y && \
    apt-get install -y openjdk-11-jdk wget curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create Spark directory and download Spark ${SPARK_VERSION}
RUN mkdir -p ${SPARK_HOME} && \
    mkdir -p ${SPARK_HOME}/logs && \
    wget -P /opt https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz && \
    tar -xzf /opt/spark-${SPARK_VERSION}-bin-hadoop3.tgz -C ${SPARK_HOME} --strip-components=1 && \
    rm /opt/spark-${SPARK_VERSION}-bin-hadoop3.tgz

#RUN touch ${SPARK_HOME}/conf/spark-defaults.conf
# Copy spark-defaults.conf (will be mounted from volume in docker-compose)
#COPY spark_config/spark-defaults.conf ${SPARK_HOME}/conf/spark-defaults.conf

# Download JARs for Iceberg, Hadoop AWS, and AWS SDK v2
# Download iceberg spark runtime
RUN curl https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-${SPARK_MAJOR_VERSION}_2.12/${ICEBERG_VERSION}/iceberg-spark-runtime-${SPARK_MAJOR_VERSION}_2.12-${ICEBERG_VERSION}.jar -Lo ${SPARK_HOME}/jars/iceberg-spark-runtime-${SPARK_MAJOR_VERSION}_2.12-${ICEBERG_VERSION}.jar

# Download AWS bundle
RUN curl -s https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-aws-bundle/${ICEBERG_VERSION}/iceberg-aws-bundle-${ICEBERG_VERSION}.jar -Lo ${SPARK_HOME}/jars/iceberg-aws-bundle-${ICEBERG_VERSION}.jar

# Switch back to airflow user
USER airflow

# Install Python dependencies for Spark and Iceberg
RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark==4.3.0 \
    pyspark==${SPARK_VERSION} \
    polars==1.34.0 \
    faker==37.11.0

# Expose ports (will be mapped in docker-compose)
EXPOSE 8080 18080 7077 4040

