name : highlands_coffee
services:
  minio:
    hostname: minio
    container_name: minio
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DOMAIN=minio
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      data_net:
        aliases:
          - mycatalog.minio
          # - highlands-coffee-warehouse.minio

  iceberg-rest:
    hostname: iceberg-rest
    image: tabulario/iceberg-rest:latest
    container_name: iceberg-rest
    ports:
      - "8181:8181"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://mycatalog/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_PATH_STYLE_ACCESS=true
      - CATALOG_S3_FORCE_PATH_STYLE=true
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - data_net

  prefect:
    image: prefecthq/prefect:3-latest
    container_name: prefect
    command: >
      prefect server start --host 0.0.0.0 --port 4200
    environment:
      PREFECT_API_URL: http://localhost:4200/api
    ports:
      - "4200:4200"
    volumes:
      - ./prefect:/root/.prefect
    networks:
      - data_net


  # --- Dask Scheduler ---
  dask-scheduler:
    image: daskdev/dask:latest
    container_name: dask-scheduler
    command: bash -c "pip install --no-cache-dir s3fs==2025.2.0 && dask scheduler"
    ports:
      - "8786:8786"   # scheduler
      - "8787:8787"   # dashboard
    volumes:
      - ./dask:/workspace
    networks:
      - data_net

  # --- Dask Workers ---
  dask-worker:
    image: daskdev/dask:latest
    depends_on:
      - dask-scheduler
    command: bash -c "pip install --no-cache-dir s3fs==2025.2.0 && dask worker tcp://dask-scheduler:8786"
    deploy:
      replicas: 2
    volumes:
      - ./dask:/workspace
    networks:
      - data_net

  # --- DuckDB + PyIceberg Environment ---
  duckdask:
    build:
      context: ./services_config
      dockerfile: Dockerfile.duck_dask
    container_name: duckdask
    working_dir: /app
    command: tail -f /dev/null
    environment:
      PYICEBERG_CATALOG__MYCATALOG__URI: http://iceberg-rest:8181
      PYICEBERG_CATALOG__MYCATALOG__TYPE: rest
      PYICEBERG_CATALOG__MYCATALOG__S3__ENDPOINT: http://minio:9000
      PYICEBERG_CATALOG__MYCATALOG__S3__ACCESS_KEY_ID: minioadmin
      PYICEBERG_CATALOG__MYCATALOG__S3__SECRET_ACCESS_KEY: minioadmin
      PREFECT_API_URL: http://prefect:4200/api
      AWS_REGION: us-east-1
    volumes:
      - ./notebooks:/app
    depends_on:
      - iceberg-rest
      - minio
    networks:
      - data_net

  # --- Apache Superset ---
  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      SUPERSET_SECRET_KEY: "supersecretkey"
      SUPERSET_ADMIN_USERNAME: admin
      SUPERSET_ADMIN_PASSWORD: admin
      SUPERSET_ADMIN_EMAIL: admin@superset.com
    ports:
      - "8088:8088"
    ## Chạy lần đầu tiên để tạo user admin
    # commands:
    #   - superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@example.com --password admin
    #   - superset db upgrade
    #   - superset init
    depends_on:
      - duckdask
    volumes:
      - ./superset:/app/superset_home
    networks:
      - data_net

volumes:
  minio_data:

networks:
  data_net:
    driver: bridge