# Cấu hình Trino Coordinator
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=5GB
query.max-memory-per-node=512MB
# Bỏ qua: query.max-total-memory-per-node=2GB
# Tên node sẽ được sử dụng để đăng ký trên network
node.environment=production